Added init (repo|self)

diff --git a/go-build b/go-build
--- a/go-build
+++ b/go-build
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 GOBUILD_ROOT="__GOBUILD_ROOT__"
+GOBUILD_BIN="__GOBUILD_BIN__"
 cd $GOBUILD_ROOT
 
 GO_REPO_URI="https://go.googlecode.com/hg/"
@@ -62,12 +63,28 @@ versions() {
 }
 
 upgrade() {
-    if [ "${1}" = "help" ]; then
-        upgrade_usage
-    fi
-    
-    cd $GO_REPO_DIR
-    hg pull
+    _OPT="${1}"
+
+    case "${_OPT}" in
+        help)
+            upgrade_usage
+            ;;
+        repo)
+            cd $GO_REPO_DIR
+            hg pull
+            ;;
+        self)
+            cd $GOBUILD_ROOT
+            git pull
+            export $GOBUILD_ROOT
+            export $GOBUILD_BIN
+            cat install-go-build | bash
+            ;;
+        *)
+            echo "Command not found : ${_OPT}"
+            exit 1
+            ;;
+    esac
 }
 
 usage() {
@@ -77,7 +94,7 @@ Options:
     init     initialize go-build
     install  install go
     versions display versions
-    upgrade  upgrade go repository
+    upgrade  upgrade go repository and go-build
 "
     exit 1
 }
@@ -122,10 +139,12 @@ Options:
 upgrade_usage() {
             echo "Usage: $(basename $0) upgrade
 
-Execute hg pull
+Upgrade go repo and go-build
 
 Options:
     help Show this help message
+    repo Upgrade go repo
+    self Upgrade go-build
 "
     exit 1
 }
